// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _06_EF_CodeFitrs;

#nullable disable

namespace _06_EF_CodeFitrs.Migrations
{
    [DbContext(typeof(Company_db))]
    [Migration("20250317172210_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectWorker", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<int>("WorkersNumber")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId", "WorkersNumber");

                    b.HasIndex("WorkersNumber");

                    b.ToTable("ProjectWorker");
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Poland"
                        });
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Position", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Management",
                            Prone = "45-45-23412"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Programing",
                            Prone = "45-45-23412"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Design",
                            Prone = "45-45-23412"
                        });
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LaunchDate = new DateTime(1982, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tetris"
                        },
                        new
                        {
                            Id = 2,
                            LaunchDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CS"
                        },
                        new
                        {
                            Id = 3,
                            LaunchDate = new DateTime(1999, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PacMan"
                        });
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Worker", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.HasKey("Number");

                    b.HasIndex("CountryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Number = 1,
                            Birthdate = new DateTime(2005, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 1,
                            DepartmentId = 1,
                            Name = "Emma",
                            Salary = 2700.0,
                            Surname = "Miller"
                        },
                        new
                        {
                            Number = 2,
                            Birthdate = new DateTime(2005, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 2,
                            DepartmentId = 2,
                            Name = "Taras",
                            Salary = 5800.0,
                            Surname = "Bondar"
                        },
                        new
                        {
                            Number = 3,
                            Birthdate = new DateTime(2012, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 3,
                            DepartmentId = 3,
                            Name = "Tomm",
                            Salary = 3200.0,
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("ProjectWorker", b =>
                {
                    b.HasOne("_06_EF_CodeFitrs.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_06_EF_CodeFitrs.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkersNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Worker", b =>
                {
                    b.HasOne("_06_EF_CodeFitrs.Entities.Country", "Country")
                        .WithMany("Workers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_06_EF_CodeFitrs.Entities.Department", "Department")
                        .WithMany("Workers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Country", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("_06_EF_CodeFitrs.Entities.Department", b =>
                {
                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
